server:
  port: 8080  # порт, на котором работает приложение

spring:
  datasource:
    url: jdbc:h2:mem:testdb # подключение к H2 в памяти
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create  # при запуске пересоздаёт таблицы
    show-sql: true  # печатать SQL-запросы в консоль

logging:
  level:
    root: INFO  # уровень логгирования